css/common.css

Added different open sourced font to the code segments in the getting started section to address the fact that our font was not very code-esque aesthetically

font addition

---

css/common.css
css/gettingStarted.css
css/packages.css
dist/gettingStarted.js
dist/packages.js
en/gettingStarted.html
en/index.html
package-lock.json
package.json
ts/gettingStarted.ts
ts/packages.ts

Added hover over text for compatibilities, copying to clipboard, changed cursor to pointer for package card. This is for better visibility for vision impaired people.

added hover over text

---

css/common.css
css/gettingStarted.css
css/packages.css
dist/gettingStarted.js
dist/packages.js
en/packages.html
ts/gettingStarted.ts
ts/packages.ts

Fixed alt text hover over other text, added alt text for package install.

added more alt text on packages install tab

---

css/packages.css
dist/packages.js
ts/packages.ts

Improve wording on alt texts, less confusing on compatibility filters.

better wording on alt text

---

css/index.css

adding css to make gif a big bigger.

gif style update

---

dist/packages.js
en/gettingStarted.html
ts/packages.ts

When a user types a letter into the search bar of the packages tab, the query parameter of the URL now updates. This behavior is inspired by that of vcpkgx.com

Update URL on key press for package tab

---

package-lock.json
package.json

There are several unused node modules in our packages.json that trigger dependabot security alerts.
Fixes #82 #69 #68

Trim node modules

---

en/index.html

Fixes the z-ordering issue on the index page

---

dist/localization.js

remove index html from home page url

remove index html from home page url

---

en/getting-started.html
en/index.html
en/packages.html
scripts/validateLinks.js
templates/footer.html
templates/index.html
templates/navbar.html

remove .html from urls

---

css/getting-started.css
en/getting-started.html
templates/getting-started.html

this pull request fixes the following issues
- Accessibility - vcpkg - List error
- Accessibility - vcpkg - color-contrast errors
- Accessibility - vcpkg - aria-required-parent errors

accessability fixes for vcpkg

---

dist/common.js
en/packages.html
templates/packages.html

This pull request fix for the following work items
- https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1826568
- https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1826566

Hamberger menu focus fix

---

dist/common.js
en/getting-started.html
en/index.html
en/packages.html
templates/getting-started.html
templates/index.html
templates/packages.html

This pull request fixes the issue  #1827419
https://devdiv.visualstudio.com/DevDiv/_queries/edit/1827419

Main landmark accessability fixes

---

.github/workflows/sync-package-periodically.yml
.github/workflows/validate.yml

removed 'Check for differences' task to verify that commit.txt is reflected with the latest commit id.

remove check difference run task

---

.github/workflows/sync-package-periodically.yml

Fixes:
remote: error: GH00[6](https://github.com/vcpkg/vcpkg.github.io/actions/runs/6730524975/job/18293379565#step:6:6): Protected branch update failed for refs/heads/main.        
remote: error: Changes must be made through a pull request.        
To https://github.com/vcpkg/vcpkg.github.io.git
! [remote rejected] HEAD -> main (protected branch hook declined)
error: failed to push some refs to 'https://github.com/vcpkg/vcpkg.github.io.git'
Error occurred while push to origin

[PackageSync] Create a pull request instead of pushing to main

---

css/package.css

this fixes accessibility issues for the below pages
- https://vcpkg.io/en/package/boost-core.html
- https://vcpkg.io/en/package/boost-static-assert.html
- https://vcpkg.io/en/package/boost-config.html
- https://vcpkg.io/en/package/boost-integer.html
- https://vcpkg.io/en/package/boost-container-hash.html
- https://vcpkg.io/en/package/boost-coroutine.html
- https://vcpkg.io/en/package/boost-assert.html
- https://vcpkg.io/en/package/boost-atomic.html
- https://vcpkg.io/en/package/boost-iterator.html
- https://vcpkg.io/en/package/boost-concept-check.html
- https://vcpkg.io/en/package/boost-mpl.html
- https://vcpkg.io/en/package/boost-type-traits.html
- https://vcpkg.io/en/package/boost-tuple.html
- https://vcpkg.io/en/package/boost-parameter.html
- …

accessability fixes for detailed package

---

scripts/consentAndAnalytics.js

Implement consent details  foe cookie consent banner data refer the [work item](https://devdiv.visualstudio.com/DevDiv/_queries/edit/2129500)

implement consent details for cookie consent banner data

---

css/common.css

Footer heading in common.css was modified for ticket  id 2253640. @JavierMatosD - Can you please review this.

Modified common css for ticket id 2253640.

---

css/packages.css

fixes #2398222
Ticket: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2398222/
Before changes - no outline for search results
After Changes

bug fixes - 2398222

---

css/common.css

fixes #2395773
Ticket: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2395773/
Before changes
After changes

bug fix - 2395773

---

css/common.css

fixed line height
